/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:776741:
  appc.background(230);
} //_CODE_:window1:776741:

public void date1Changed(GTextField source, GEvent event) { //_CODE_:date1:955750:
  if(start == false){
    startDate = date1.getText();
  }
} //_CODE_:date1:955750:

public void tempSliderChanged(GSlider source, GEvent event) { //_CODE_:tempSlider:201894:
  if(start == false){
    temp = tempSlider.getValueF();
  }
} //_CODE_:tempSlider:201894:

public void startButtonClicked(GButton source, GEvent event) { //_CODE_:startButton:297293:
  if(start == false){
    start =! start;
  }
  
} //_CODE_:startButton:297293:

public void vacationTypeChanged(GDropList source, GEvent event) { //_CODE_:vacationTypeList:754772:
  if(start == false){
    typeVacation = vacationTypeList.getSelectedText();
  }
} //_CODE_:vacationTypeList:754772:

public void englishBoxClicked(GCheckbox source, GEvent event) { //_CODE_:englishBox:524859:
  if(start == false){  
    engLanguage =! engLanguage;
  }
} //_CODE_:englishBox:524859:

public void budgetTypeChanged(GDropList source, GEvent event) { //_CODE_:budgetTypeList:831911:
  if(start == false){  
    budget = budgetTypeList.getSelectedText();
  }
} //_CODE_:budgetTypeList:831911:

public void date2Changed(GTextField source, GEvent event) { //_CODE_:date2:313793:
  if(start == false){
    endDate = date2.getText();
  }
} //_CODE_:date2:313793:

public void locationStartChanged(GDropList source, GEvent event) { //_CODE_:locationStart:382412:
  if(start == false){
   startLocation = locationStart.getSelectedText();
  }


} //_CODE_:locationStart:382412:

public void roomsChanged(GTextField source, GEvent event) { //_CODE_:rooms:768867:
  if(start == false){
    numRooms = int(rooms.getText());
  }
} //_CODE_:rooms:768867:

public void resetButtonClicked(GButton source, GEvent event) { //_CODE_:resetButton:932364:
  if(start == true){
    clear();
    setup();
  }
} //_CODE_:resetButton:932364:

public void peopleNumChanged(GTextField source, GEvent event) { //_CODE_:peopleNum:316409:
  numPeople = int(peopleNum.getText());
} //_CODE_:peopleNum:316409:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 650, 650, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  date1 = new GTextField(window1, 187, 361, 81, 30, G4P.SCROLLBARS_NONE);
  date1.setText("01/22");
  date1.setPromptText("MM/DD");
  date1.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  date1.setOpaque(true);
  date1.addEventHandler(this, "date1Changed");
  tempSlider = new GSlider(window1, 71, 104, 184, 60, 10.0);
  tempSlider.setShowValue(true);
  tempSlider.setShowLimits(true);
  tempSlider.setLimits(0, -50, 50);
  tempSlider.setNbrTicks(8);
  tempSlider.setShowTicks(true);
  tempSlider.setNumberFormat(G4P.INTEGER, 0);
  tempSlider.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  tempSlider.setOpaque(false);
  tempSlider.addEventHandler(this, "tempSliderChanged");
  startButton = new GButton(window1, 548, 544, 83, 38);
  startButton.setText("CALCULATE");
  startButton.addEventHandler(this, "startButtonClicked");
  vacationTypeList = new GDropList(window1, 523, 103, 100, 88, 3, 10);
  vacationTypeList.setItems(loadStrings("list_754772"), 0);
  vacationTypeList.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  vacationTypeList.addEventHandler(this, "vacationTypeChanged");
  englishBox = new GCheckbox(window1, 83, 232, 155, 36);
  englishBox.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  englishBox.setText("English Speaking Country");
  englishBox.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  englishBox.setOpaque(false);
  englishBox.addEventHandler(this, "englishBoxClicked");
  budgetTypeList = new GDropList(window1, 526, 242, 90, 80, 3, 10);
  budgetTypeList.setItems(loadStrings("list_831911"), 0);
  budgetTypeList.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  budgetTypeList.addEventHandler(this, "budgetTypeChanged");
  label1 = new GLabel(window1, 32, 86, 266, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Temperature Slider (adjust with slider below):");
  label1.setLocalColorScheme(GCScheme.RED_SCHEME);
  label1.setOpaque(false);
  date2 = new GTextField(window1, 187, 322, 81, 30, G4P.SCROLLBARS_NONE);
  date2.setText("03/10");
  date2.setPromptText("Enter: MM/DD");
  date2.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  date2.setOpaque(true);
  date2.addEventHandler(this, "date2Changed");
  date1Label = new GLabel(window1, 24, 367, 136, 21);
  date1Label.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  date1Label.setText("Return Date(MM/DD):");
  date1Label.setLocalColorScheme(GCScheme.RED_SCHEME);
  date1Label.setOpaque(false);
  date2Label = new GLabel(window1, 23, 323, 141, 20);
  date2Label.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  date2Label.setText("Departure Date(MM/DD):");
  date2Label.setLocalColorScheme(GCScheme.RED_SCHEME);
  date2Label.setOpaque(false);
  locationStart = new GDropList(window1, 113, 457, 88, 126, 5, 10);
  locationStart.setItems(loadStrings("list_382412"), 0);
  locationStart.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  locationStart.addEventHandler(this, "locationStartChanged");
  vacationTypeLabel = new GLabel(window1, 355, 93, 155, 37);
  vacationTypeLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  vacationTypeLabel.setText("Choose a type of vacation:");
  vacationTypeLabel.setLocalColorScheme(GCScheme.RED_SCHEME);
  vacationTypeLabel.setOpaque(false);
  label2 = new GLabel(window1, 28, 198, 276, 38);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Would you like an English-speaking country? Check the box below for  (Yes):");
  label2.setLocalColorScheme(GCScheme.RED_SCHEME);
  label2.setOpaque(false);
  label3 = new GLabel(window1, 68, 419, 179, 44);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Where is your closest airport? Select from drop down list:");
  label3.setLocalColorScheme(GCScheme.RED_SCHEME);
  label3.setOpaque(false);
  label4 = new GLabel(window1, 358, 207, 152, 80);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("What is your budget? Select from drop down list: $=Cheap, $$=Average, $$$=Expensive");
  label4.setLocalColorScheme(GCScheme.RED_SCHEME);
  label4.setOpaque(false);
  label5 = new GLabel(window1, 385, 367, 206, 61);
  label5.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label5.setText("How many people on this vacation? Select from drop down list:");
  label5.setLocalColorScheme(GCScheme.RED_SCHEME);
  label5.setOpaque(false);
  lalbel6 = new GLabel(window1, 66, 514, 95, 28);
  lalbel6.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lalbel6.setText("Number of hotel rooms:");
  lalbel6.setLocalColorScheme(GCScheme.RED_SCHEME);
  lalbel6.setOpaque(false);
  rooms = new GTextField(window1, 187, 512, 81, 30, G4P.SCROLLBARS_NONE);
  rooms.setText("1");
  rooms.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  rooms.setOpaque(true);
  rooms.addEventHandler(this, "roomsChanged");
  resetButton = new GButton(window1, 548, 590, 83, 37);
  resetButton.setText("RESET");
  resetButton.setLocalColorScheme(GCScheme.RED_SCHEME);
  resetButton.addEventHandler(this, "resetButtonClicked");
  peopleNum = new GTextField(window1, 443, 436, 84, 30, G4P.SCROLLBARS_NONE);
  peopleNum.setText("1");
  peopleNum.setPromptText("BLUE_SCHEME");
  peopleNum.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  peopleNum.setOpaque(true);
  peopleNum.addEventHandler(this, "peopleNumChanged");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GTextField date1; 
GSlider tempSlider; 
GButton startButton; 
GDropList vacationTypeList; 
GCheckbox englishBox; 
GDropList budgetTypeList; 
GLabel label1; 
GTextField date2; 
GLabel date1Label; 
GLabel date2Label; 
GDropList locationStart; 
GLabel vacationTypeLabel; 
GLabel label2; 
GLabel label3; 
GLabel label4; 
GLabel label5; 
GLabel lalbel6; 
GTextField rooms; 
GButton resetButton; 
GTextField peopleNum; 
