/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:473606:
  appc.background(230);
} //_CODE_:window1:473606:

public void tempSliderChanged(GSlider source, GEvent event) { //_CODE_:tempSlider:853707:
  temp = tempSlider.getValueF();//whatever user picked
} //_CODE_:tempSlider:853707:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:914413:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield1:914413:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 240, 120, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  tempSlider = new GSlider(window1, 129, 42, 100, 40, 10.0);
  tempSlider.setLimits(0.0, -100.0, 100.0);
  tempSlider.setNumberFormat(G4P.DECIMAL, 2);
  tempSlider.setOpaque(false);
  tempSlider.addEventHandler(this, "tempSliderChanged");
  textfield1 = new GTextField(window1, 17, 46, 100, 30, G4P.SCROLLBARS_NONE);
  textfield1.setText("Temperature");
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change1");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GSlider tempSlider; 
GTextField textfield1; 
